SUPABASE_URL= "https://kgazpnmzmluyatzvmhgk.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYXpwbm16bWx1eWF0enZtaGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1NzI5NzUsImV4cCI6MjA5NDE0ODk3NX0.HUC073HKilnxdw1Nb2OvEcXTLYO7EhqxjfJy1Mb3C0c"